name: Deploy to Github Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Create env file
        run: |
          echo "${{ env.HOST }}" > .env
          echo "${{ env.HCAPTCHA_SECRET }}" > .env
          echo "${{ env.HCAPTCHA_SITEKEY }}" > .env
          echo "${{ env.SMTP_HOST }}" > .env
          echo "${{ env.SMTP_LOGIN }}" > .env
          echo "${{ env.SMTP_PASS }}" > .env
          echo "${{ env.REQUESTS_MAIL }}" > .env
      - name: Build
        run: |
          npm i --legacy-peer-deps
          npm run build
          npm run export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
